apiVersion: batch/v1
kind: CronJob
metadata:
  name: libreserve
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: Libreserve
            image: us-central1-docker.pkg.dev/libreserve/docker/libreserve:latest